language: python
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create -n prysmci python=3.7 --yes
  - source activate prysmci
  - >-
      conda install --yes
      numpy>=1.15
      scipy>=1.2
      astropy>=3.2.1
      matplotlib>=3.0
      scikit-image
      imageio
      pandas
      h5py
      pytest=5.1.2
      pytest-cov=2.8.1
      coveralls==2.0.0
  - pip install .
services:
  - xvfb
script:
  - pytest --cov=prysm tests/
notifications:
  email: false
after_success:
  - coveralls
